= jQAssistant SARIF Report Plugin

This is the SARIF Report Plugin of https://jqassistant.org[jQAssistant^].

It allows to generate JSON files in the https://docs.oasis-open.org/sarif/sarif/v2.1.0/cs01/sarif-v2.1.0-cs01.html[SARIF format] which can be used to display them e.g. in https://github.com[GitHub] pull requests.

For more information on jQAssistant see https://jqassistant.org[^].

NOTE: Despite linking of source locations is implemented by this plugin the generated links are not valid yet.
This requires a https://github.com/jQAssistant/jqassistant/issues/1077[change in jQAssistant] which is scheduled for one of the next releases.

== Setup

The plugin must be declared in the jQAssistant configuration:

[source,yaml]
..jqassistant.yml
----
jqassistant:
  plugins:
    - group-id: org.jqassistant.plugin
      artifact-id: jqassistant-sarif-report-plugin
      version: 1.0.0-M1
----
**Configuration:**

You can optionally configure, how the report messages are formatted since a couple of platforms do support a minimum of Markdown display. The Example will show the default configuration:

[source,yaml]
..jqassistant.yml
----
  analyze:
    report:
      properties:
        sarif:
          report:
            message:
              text: full       #valid inputs: title, details
              markdown: full   #valid inputs: title, details, none

----
**Available Attributes:**

[cols="1h,3"]
|===
| `title`
|contains a short description of the issue

| `details`
|contains details about the issue's location and the type of code element the issue is attached to

| `full`
|contains the full information of both `title` and `details`

| `none`
|does not contain information and can only be used in the `markdown` attribute

|===

**Recommended Platform Settings:**

[cols="1h,2", option="header"]
|===
|Target Platform |Recommended Configuration

|GitHub & Jenkins
|`text: title` +
`markdown: details`

|SonarQube
|`text: full` +
`markdown: none`

|===

Use at least version 2.10.0 of jQAssistant:

[source,xml]
.pom.xml
----
<properties>
   <jqassistant.version>2.10.0-M2</jqassistant.version>
</properties>
----
During execution of the `analyze` task or goal a file `jqassistant-sarif-report.json` is created in the report directory.

=== Upload to GitHub
Upload to GitHub must be declared in `.github/workflows/`. The jQAssistant findings will appear in the `Security and Quality` tab on GitHub.

Find an Example workflow below:

[source,yaml]
.ci.yml
----
name: generate and upload SARIF
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: build
        # build your project before upload to generate SARIF-findings
      - name: Upload SARIF-Report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ./target/jqassistant/report/sarif/jqassistant-sarif-report.json
          category: jQAssistant
          ref: ${{ github.ref }}
          sha: ${{ github.sha }}
----

=== Upload to Jenkins

==== 1. Jenkins-Setup:

- install the **Warnings**(or Warnings-ng)-Plugin. You may need to restart your container to complete the installation.

==== 2. Configuration of Jenkins-Job
- add the SARIF Issues in the `post{}` section of your Jenkinsfile
- after execution a **jQAssistant Warnings** tab will be available in the lefthand sidebar

[source,Jenkinsfile]
.Jenkinsfile
----
pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    stages {
        // Scanning and generating reports during the projects build proccess
        stage('Build & Analyze') {
           ...
        }
    }

    post {
        always {
            // capturing the issues on jenkins
            recordIssues(
                tool: sarif(pattern: 'target/jqassistant/report/sarif/jqassistant-sarif-report.json'),
                id: 'jQAssistant',
                name: 'jQAssistant'
            )
        }
    }
}
----

=== Upload to SonarQube (for maven-based Projects)

==== 1. Upload to SonarServer
- add `-Dsonar.sarifReportPaths=target/jqassistant/report/sarif/jqassistant-sarif-report.json` at the end of your commandline call

==== 2. Upload to SonarCloud

- Save your sonar token in the secrets of your Repository on GitHub
- add the following code to your `ci.yml`

[source,yaml]
.ci.yml
----
jobs:
  build-and-upload:
    name: Upload to SonarCloud
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-java@v4
       with:
         distribution: 'temurin'
         java-version: '17'
     - name: Build and Analyze
       run: |
         mvn verify --batch-mode sonar:sonar \
         -Dsonar.host.url=https://sonarcloud.io \
         -Dsonar.projectKey=<YOUR PROJECTKEY> \
         -Dsonar.organization=<YOUR ORGANIZATION> \
         -Dsonar.sarifReportPaths=target/jqassistant/report/sarif/jqassistant-sarif-report.json
       env:
         SONAR_TOKEN: ${{ secrets.sonar_token }}
----
