= jQAssistant SARIF Report Plugin

This is the SARIF Report Plugin of https://jqassistant.org[jQAssistant^].

It allows to generate JSON files in the https://docs.oasis-open.org/sarif/sarif/v2.1.0/cs01/sarif-v2.1.0-cs01.html[SARIF format] which can be used to display them e.g. in https://github.com[GitHub] pull requests.

For more information on jQAssistant see https://jqassistant.org[^].

NOTE: Despite linking of source locations is implemented by this plugin the generated links are not valid yet.
This requires a https://github.com/jQAssistant/jqassistant/issues/1077[change in jQAssistant] which is scheduled for one of the next releases.

== Setup

The plugin must be declared in the jQAssistant configuration:

[source,yaml]
..jqassistant.yml
----
jqassistant:
  plugins:
    - group-id: org.jqassistant.plugin
      artifact-id: jqassistant-sarif-report-plugin
      version: 1.0.0-M1
----

Use at least version 2.10.0 of jQAssistant:

[source,xml]
.pom.xml
----
<properties>
   <jqassistant.version>2.10.0-M2</jqassistant.version>
</properties>
----
During execution of the `analyze` task or goal a file `jqassistant-sarif-report.json` is created in the report directory.

=== Upload to Jenkins

==== 1. Jenkins-Setup:

- install the **Warnings**-Plugin. You may need to restart your container to complete the installation.

==== 2. Configuration of Jenkins-Job
- add the SARIF Issues in the `post{}` section of your Jenkinsfile as shown below
- after execution a **jQAssistant Warnings** tab will be available in the lefthand sidebar

[source,Jenkinsfile]
.Jenkinsfile
----
pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    stages {
        // Scanning and generating reports during the projects build proccess
        stage('Build & Analyze') {
           ...
        }
    }

    post {
        always {
            // capturing the issues on jenkins
            recordIssues(
                tool: sarif(pattern: 'target/jqassistant/report/sarif/jqassistant-sarif-report.json'),
                id: 'jQAssistant',
                name: 'jQAssistant'
            )
        }
    }
}
----

