= jQAssistant SARIF Report Plugin

This is the SARIF Report Plugin of https://jqassistant.org[jQAssistant^].

It allows to generate JSON files in the https://docs.oasis-open.org/sarif/sarif/v2.1.0/cs01/sarif-v2.1.0-cs01.html[SARIF format] which can be used to display them e.g. in https://github.com[GitHub] pull requests.

For more information on jQAssistant see https://jqassistant.org[^].

NOTE: Despite linking of source locations is implemented by this plugin the generated links are not valid yet.
This requires a https://github.com/jQAssistant/jqassistant/issues/1077[change in jQAssistant] which is scheduled for one of the next releases.

== Setup

The plugin must be declared in the jQAssistant configuration:

[source,yaml]
..jqassistant.yml
----
jqassistant:
  plugins:
    - group-id: org.jqassistant.plugin
      artifact-id: jqassistant-sarif-report-plugin
      version: 1.0.0-M1
----
You can additionally configure, how the report-message will be displayed since a couple of platforms do support a minimum of Markdown display:

[source,yaml]
..jqassistant.yml
----
  analyze:
    report:
      properties:
        sarif:
          report:
            message:
              text: title       #valid inputs: full, details
              markdown: details #valid inputs: full, title, none

----

Use at least version 2.10.0 of jQAssistant:

[source,xml]
.pom.xml
----
<properties>
   <jqassistant.version>2.10.0-M2</jqassistant.version>
</properties>
----
During execution of the `analyze` task or goal a file `jqassistant-sarif-report.json` is created in the report directory.

=== Upload to GitHub
Upload to GitHub must be declared in `.github/workflows/`.The jQAssistant findings will appear in the `Security and Quality` tab on GitHub.

Find an Example workflow below:

[source,yaml]
.ci.yml
----
name: generate and upload SARIF
jobs:
  build:
    name: build
    runs-on: ubuntu-lastest
    permissions:
      security-events: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: build
        # build your project before upload to generate SARIF-findings
      - name: Upload SARIF-Report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ./target/jqassistant/report/sarif/jqassistant-sarif-report.json
          category: jQAssistant
          ref: ${{ github.ref }}
          sha: ${{ github.sha }}
----

=== Upload to Jenkins

==== 1. Jenkins-Setup:

- install the **Warnings**-Plugin. You may need to restart your container to complete the installation.

==== 2. Configuration of Jenkins-Job
- add the SARIF Issues in the `post{}` section of your Jenkinsfile as shown below
- after execution a **jQAssistant Warnings** tab will be available in the lefthand sidebar

[source,Jenkinsfile]
.Jenkinsfile
----
pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    stages {
        // Scanning and generating reports during the projects build proccess
        stage('Build & Analyze') {
           ...
        }
    }

    post {
        always {
            // capturing the issues on jenkins
            recordIssues(
                tool: sarif(pattern: 'target/jqassistant/report/sarif/jqassistant-sarif-report.json'),
                id: 'jQAssistant',
                name: 'jQAssistant'
            )
        }
    }
}
----

=== Upload to SonarQube/SonarCloud

==== 1. Upload to SonarServer
- make sure to run your build with `mvn install` instead of `mvn verify` in order to actually generate the SARIF
- add `-Dsonar.sarifReportPaths=target/jqassistant/report/sarif/jqassistant-sarif-report.json` at the end of your commandline call

