= jQAssistant SARIF Report Plugin

This is the SARIF Report Plugin of https://jqassistant.org[jQAssistant^].

It allows to generate JSON files in the https://docs.oasis-open.org/sarif/sarif/v2.1.0/cs01/sarif-v2.1.0-cs01.html[SARIF format] which can be used to display them e.g. in https://github.com[GitHub] pull requests.

For more information on jQAssistant see https://jqassistant.org[^].

NOTE: Despite linking of source locations is implemented by this plugin the generated links are not valid yet.
This requires a https://github.com/jQAssistant/jqassistant/issues/1077[change in jQAssistant] which is scheduled for one of the next releases.

== Setup

The plugin must be declared in the jQAssistant configuration:

[source,yaml]
..jqassistant.yml
----
jqassistant:
  plugins:
    - group-id: org.jqassistant.plugin
      artifact-id: jqassistant-sarif-report-plugin
      version: 1.0.0-M1
----

Please also ensure use of the necessary jQAssistant version in your pom.xml:

[source,xml]
.pom.xml
----
<properties>
   <jqassistant.version>2.10.0-M2</jqassistant.version>
</properties>
----
During execution of the `analyze` task or goal a file `jqassistant-sarif-report.json` is created in the report directory.

=== Upload to Jenkins

==== 1. Jenkins-Setup:
- create a local jenkins-image, ensure to deploy the official Jenkins Long Term Support image
- example command for docker:

[source,bash]
----
docker run -p 8080:8080 jenkins/jenkins:lts
----
- find your password in your terminal logs, your default username should be 'admin'. You will be able to change that data later
- (if not present yet) add a Maven and Git Installation in **manage-jenkins** (settings-wheel in the top-right corner) -> **Tools**
- install the **Warnings**-Plugin in **manage-jenkins** -> **Plugins**. You may need to restart your container to complete the installation.

==== 2. Configuration of Jenkins-Job
- add the `Jenkinsfile` below to the root directory of your repository
- create a new element for your project using item type **pipeline**
- navigate to the Pipeline-section
- Set the Definition field to **Pipeline script from SCM**

- finally select **save** and **build now** to execute your build
- after execution a **jQAssistant Warnings** tab will be available in the lefthand sidebar

[source,Jenkinsfile]
.Jenkinsfile
----
pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    stages {
        stage('Build & Analyze') {
            steps {
                sh 'mvn clean verify'
            }
        }
        stage('Archive Results') {
            steps {
                archiveArtifacts artifacts: 'target/jqassistant/report/sarif/jqassistant-sarif-report.json',
                                 fingerprint: true,
                                 onlyIfSuccessful: true
            }
        }
    }

    post {
        always {
            recordIssues(
                tool: sarif(pattern: 'target/jqassistant/report/sarif/jqassistant-sarif-report.json'),
                id: 'jQAssistant',
                name: 'jQAssistant'
            )
        }
    }
}
----

